# Generated by Django 2.1.11 on 2019-08-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190827_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(help_text='Enter comment about blog here.', max_length=10000),
        ),
    ]
