# Generated by Django 2.1.11 on 2019-08-27 23:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190827_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='blogger',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='blogger',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
