# Generated by Django 2.1.11 on 2019-08-27 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190828_0227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogger',
            options={'ordering': ['user']},
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='created',
        ),
    ]
